{
 "title": "Serverless Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "environment", "label": "Environment", "query": "azure-local, azure-cloud," }
  ]
 },
 "panels": [
  { "title": "Cost Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GB-Seconds reported by Azure Monitor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "azure_monitor_gigabyteseconds_total",
     "legendFormat": "{{function_app}}"
    }
   ]
  },
  {
   "title": "Estimated Execution Units Cost",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "currencyEUR" }
   ],
   "targets": [
    {
     "expr": "function_gigabyte_seconds_total{environment=\"$environment\"}*0.000014",
     "legendFormat": "{{function_app}}:{{function_name}}"
    }
   ]
  },
  {
   "title": "Calculated Invocation Cost",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "currencyEUR" }
   ],
   "targets": [
    {
     "expr": "function_invocations_total{environment=\"$environment\"}*0.000000169",
     "legendFormat": "{{function_app}}:{{function_name}}"
    }
   ]
  },
  {
   "title": "Cost Comparison: Estimated, Calculated Values vs. Actual, Reported Values (3min delay)",
   "type": "graph",
   "description": "The \"actual\" datasource will only show up if you setup a program/script which reads values from the Azure Monitor API and sends them to Prometheus Aggregator. In addition the Azure Monitor API seems to be unreliable",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "currencyEUR" }
   ],
   "targets": [
    {
     "expr": "(sum(function_gigabyte_seconds_total{environment=\"$environment\"} offset 3m) by (function_app))*0.000014",
     "legendFormat": "Estimation: {{function_app}}"
    },
    {
     "expr": "azure_monitor_gigabyteseconds_total*0.000014",
     "legendFormat": "Actual: {{function_app}}"
    }
   ]
  },
  { "title": "Execution Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 8, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(function_invocations_total{environment=\"$environment\"})-sum(function_invocations_total{environment=\"$environment\"} offset 6h)"
    }
   ]
  },
  {
   "title": "Invocations Total",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "function_invocations_total{environment=\"$environment\"}",
     "legendFormat": "{{function_app}}:{{function_name}}"
    }
   ]
  },
  {
   "title": "Execution Time Total",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "function_execution_time_total{environment=\"$environment\"}",
     "legendFormat": "{{function_app}}:{{function_name}}"
    }
   ]
  },
  {
   "title": "Reported Finished Function Executions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "function_finished_total{environment=\"$environment\"}",
     "legendFormat": "{{function_app}}:{{function_name}}"
    }
   ]
  },
  {
   "title": "Total invocations which did not reach the end",
   "type": "graph",
   "description": "Orchestrator functions of durable functions get stopped mid execution and restarted if necessary. Therefore many executions will not \"reach the end\"",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "function_invocations_total{environment=\"$environment\"} - function_finished_total{environment=\"$environment\"}",
     "legendFormat": "{{function_app}}:{{function_name}}"
    }
   ]
  },
  {
   "title": "Invocation Rate (last 5 minutes)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(function_invocations_total{environment=\"$environment\"}[5m])",
     "legendFormat": "{{function_app}}:{{function_name}}"
    }
   ]
  },
  {
   "title": "Average Execution Time in the last 5 Minutes",
   "type": "graph",
   "description": "Will only show up if enough data is available and will not work for the first 5 minutes for a function which had no data in Prometheus before",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "(function_execution_time_total{environment=\"$environment\"}-function_execution_time_total{environment=\"$environment\"} offset 5m)/(function_finished_total-function_finished_total{environment=\"$environment\"} offset 5m)",
     "legendFormat": "{{function_app}}:{{function_name}}"
    }
   ]
  },
  {
   "title": "Executions",
   "type": "graph",
   "description": "Shows executions as single points in 5 second aggregates",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "function_invocations_total{environment=\"$environment\"} - (function_invocations_total{environment=\"$environment\"} offset 5s)",
     "legendFormat": "{{function_app}}:{{function_name}}"
    }
   ]
  },
  {
   "title": "Function End Not Reached Percentage within the last hour",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "((function_invocations_total{environment=\"$environment\"} -function_invocations_total{environment=\"$environment\"} offset 1h) - (function_finished_total{environment=\"$environment\"} - function_finished_total{environment=\"$environment\"} offset 1h)) / (function_invocations_total{environment=\"$environment\"} -function_invocations_total{environment=\"$environment\"} offset 1h)",
     "legendFormat": "{{function_app}}:{{function_name}}"
    }
   ]
  }
 ]
}